### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by Garik-** [lttb/reshadow#1]

**Comment by lttb** [comment]
Hi, @Garik-!

We're looking to publish the `alpha` version this week 😄 

So stay tuned!

**Comment by pavelrevers** [comment]
In Russia, a week lasts 22 days and this is not the limit

**Comment by lttb** [comment]
Hey guys, please accept my apologies for the delay. The time to finalize the API, collect all ideas and prepare the docs took a bit more than I expected.

In fact, the `reshadow@alpha` has been recently published, so you can play around with examples on the codesandbox:
`react`: https://codesandbox.io/s/o9w535k0z6
`preact`: https://codesandbox.io/s/o5jrpk0zm5

I'll try to publish the docs and the stable version as soon as possible.

**Comment by alexmironof** [comment]
Awesome work @lttb, thanks! :tada:

**Comment by lttb** [comment]
Hi all, thank you for waiting.

I've finally published the code of the `alpha` 😄
Unfortunately, there is still a lack of documentation, so I also hope to finish the docs this week too.

Anyway, you can find some examples in the `README.md`.
There are also more examples and explanation on the docs website https://reshadow.dev (I also find some problems with site availability in Russia, so there is a mirror: https://reshadow.now.sh)

@alexmironof thank you a lot for the feedback! Please keep in note, that it's still `alpha`, so feel free to share any feedback 🙂
