### ISSUE TITLE
TypeError: Cannot convert a Symbol value to a string when I run jest test some components

### ISSUE THREAD

**Issue by s-kobets** [lttb/reshadow#103]
```
import styled from 'reshadow';
import styles from 'styles.css';

styled(styles)`...`(React.Component)
```

**Comment by antonk52** [comment]
Hi and thank you for your issue.

I have configured jest to work with reshadow before but didn’t run into this issue. From your explanation it’s quite hard to guess what went wrong. Can you provide more information? To be specific your `babel.config.js` and `jest.config.js` would be a great start. If you can provide reproducible example that would be perfect.

Thanks

**Comment by s-kobets** [comment]
I am sorry. I forget use `reshadow/babel` in jest.config.js. Thank you.
