### ISSUE TITLE
Hi. I make screenshot test for ReactComponent with @reshadow, but html element don't have style, but in browser everything ok.

### ISSUE THREAD

**Issue by s-kobets** [lttb/reshadow#104]
## Component
```
import styled from 'reshadow';

styled(styles)`
      Textarea {
        resize: ${resize};
      }
    `(
      <Textarea {...props} />
     )
```
## Use
```
<Textarea resize="both"> 
```

**Comment by lttb** [comment]
Thank you for the issue!

could you provide a bit more details please?
- are you using server side rendering, `next.js`?
- are you using just `reshadow/babel`, or `reshadow/webpack/loader`, `reshadow/postcss` too?

**Comment by s-kobets** [comment]
I use `reshadow/babel` 
I use `ReactDOM.render(Component)` - it my SSR for snapshot in Jest

**Comment by s-kobets** [comment]
### My config for transpiler babel 
```    
    'reshadow/babel',
        {
          postcss: {
            generateScopedName: function generateScopedName(name, filename, css) {
               ...
            },
            options: {
              presetEnv: {
                stage: 0,
                features: {
                  'custom-properties': {
                    preserve: false,
                  },
                  'color-mod-function': {
                    unresolved: 'error',
                  },
                },
              },
            },
            plugins: [postCssPluginInlineComment()],
          },
        }
```

**Comment by s-kobets** [comment]
Maybe it is my problem. I think, this is problem with stack in @reshadow/core?

**Comment by s-kobets** [comment]
I find problem. I was use old version jest ^24. I update all dependencies jest and it resolved my problem.

**Comment by lttb** [comment]
hi @s-kobets, please sorry for the late response.

glad you've found a solution, and thank you for sharing this!
