### ISSUE TITLE
Reshadow syntax proposal

### ISSUE THREAD

**Issue by ilyalesik** [lttb/reshadow#12]
I guess that separate style and jsx is more intuitively and understandable. I want to write some styles first, and create a component with JSX markup and some logic after that. Like this:
```javascript
import React from "react";
import styled from "reshadow";

const css = styled`
    button {
      width: 250px;
    }
    span[use|size='l'] {
       text-transform: uppercase;  
    }
`;

export const CounterButton = ({children, size, ...props}) => {
  const [count, setCount] = useState(0); 
  return css(<button {...props} onClick={() => {setCount(count + 1)}}>
      <span use:size={size}>{children} {count}</span>
  </button>);
}
```

When I watch to constructions like this
```javascript
export const CommonButton = ({ children, ...props }) =>
  styled`
    button {
      width: 250px;
    }
   span[use|size='l'] {
       text-transform: uppercase;  
    }
`(<button {...props}>
       {children}
  </button>);
```
I am experiencing cognitive stress and don't understand, what's going on. 😀

**Comment by lttb** [comment]
hi @ilyalesik, thank you for the issue!

I've got plans to support the `styled` usage in the way you described in the first example in the nearest release, so stay tuned 😃 

BTW, it is also possible to use separate styles like this:

```js
import React from "react";
import styled, {css} from "reshadow";

const styles = css`
  button {
    width: 250px;
  }
  span[use|size='l'] {
    text-transform: uppercase;  
  }
`;

export const CounterButton = ({children, size, ...props}) => {
  const [count, setCount] = useState(0); 

  return styled(styles)(
    <button {...props} onClick={() => {setCount(count + 1)}}>
      <span use:size={size}>{children} {count}</span>
    </button>
  );
}
```

and you can even move your `styles` into the separate file like `styles.css` and just import it

**Comment by ilyalesik** [comment]
Code from your comment is equal to code from my proposal, and I see that I can use reshadow at convenient for me way right now. Thanks!

**Comment by lttb** [comment]
I think we can close this issue at this moment, feel free to reopen it if you'll have any questions
