### ISSUE TITLE
Can you please provide an example with Next.js ?

### ISSUE THREAD

**Issue by VladSez** [lttb/reshadow#18]
Hello! I would like to try reshadow with Next.js. Could you provide an example?

**Comment by lttb** [comment]
Hey @VladSez, thank you for the issue.

I made an example with `next.js` with SSR on the codesandbox: https://codesandbox.io/s/reshadownextjs-h4or9

Fill free to ask for any other help :)

In general, there are a few steps to start with reshadow:
1) `npm i -S reshadow`
2)
**.babelrc**
```json
{
  "presets": [
    "next/babel"
  ],
  "plugins": [
    [
      "reshadow/babel"
    ]
  ]
}
```

In the nearby feature we're looking to add an optional support without a babel plugin, but the recommended way is still to use it with babel for better performance

**Comment by VladSez** [comment]
Thank you so much!

**Comment by lttb** [comment]
Hi @VladSez, have you tried reshadow with next.js? Do you still have an issue with that?

**Comment by VladSez** [comment]
Hi @lttb, yep, everything is good. Should i close the issue? What do you think about adding reshadow with next.js example to the docs?

**Comment by lttb** [comment]
I've added a link to the example with `next.js` on the codesandbox in README and on the website.
I think it would be also useful to create a repo with examples or something like `reshadow-awesome` with links to the examples, guides and so on

At this moment we have:
- links on the README.md
- https://github.com/quasiyoke/reshadow-example-tunes/ (WIP)
- https://github.com/lttb/reshadow/tree/master/examples

So, I'm closing this issue about next.js right now, but I would be glad for any help, ideas, examples, code etc 🙂
