### ISSUE TITLE
problem with flex style ?

### ISSUE THREAD

**Issue by paxarpp** [lttb/reshadow#24]
in this code:
```
const Divider = ({ children, max, end, start, ...props }) => (
  <Wrap max={max} end={end} start={start} {...props}>
    {children}
  </Wrap>
);
Divider.propTypes = {
  /** width = 100% */
  max: PropTypes.bool,
  /** what render on divider (text etc) */
  children: PropTypes.any,
  /** children located in the end divider */
  end: PropTypes.bool,
  /** children located in the start divider */
  start: PropTypes.bool
};
const style = css`
  content: '';
  background-color: #e0e0e0;
  height: 1px;
  flex: 1;
`;
const Wrap = styled.h4`
  display: flex;
  margin: 0 auto;
  width: ${({ max }) => (max ? '100%' : '80%')};
  align-items: center;
  :after {
    ${style};
    flex: ${({ start }) => start && '20'};
  }
  :before {
    ${style};
    flex: ${({ end }) => end && '20'};
  }
`;
export default Divider;
```
flex: ${({ start }) => start && '20'}; or with end, not work.
 return flex = 1.

replace for flex: ${({ start }) => start ? '20' : '0'}; not help.

**Comment by lttb** [comment]
hi @paxarpp!

There was an issue with mixins selectors specificity, fixed in `alpha.54`

Here is an example with Divider:
https://codesandbox.io/s/reshadowstyled-kv7qq

**Comment by paxarpp** [comment]
Good afternoon,
the location in the center did not work (when neither start nor end was transmitted), the code change helped:
```
const style = css`
  content: '';
  background-color: #e0e0e0;
  height: 1px;
  flex: 1;
`;
const isStart = ({ start }) => start && css`flex: 20}`;
const isEnd = ({ end }) => end && css`flex: 20}`;

const Wrap = styled.h4`
  display: flex;
  margin: 0 auto;
  width: ${({ max }) => (max ? '100%' : '80%')};
  align-items: center;
  :after {
    ${style};
    ${isStart}
  }
  :before {
    ${style};
    ${isEnd}
  }
`;
export default Divider;
```

Maybe I had a problem with the code with the correctness of the code?

**Comment by lttb** [comment]
> Maybe I had a problem with the code with the correctness of the code?

@paxarpp, hmm, the initial code looks correct, and I can't notice any difference in behaviour between these two snippets. here is an example with both variants: https://codesandbox.io/s/reshadowstyled-kv7qq

**Comment by lttb** [comment]
I think we can close this issue right now, but feel free to reopen it please if you'll still have this kind of problem

and thank you again for the help!
