### ISSUE TITLE
the overlying style is not redefined

### ISSUE THREAD

**Issue by paxarpp** [lttb/reshadow#25]
hi, 
if you are not tired of my questions, then here's another:
(ver 0.54 or ver 0.57)
the overlying style is not redefined, if there is a new style below:
```
const isBadge = ({ badge }) =>
  badge &&
  css`
    ${commonStyle}
    border-radius: 1rem;
    background-color: ${({ color }) => color};
  `;

export const Span = styled.span`
  margin-left: 14px;
  text-align: center;
  box-sizing: border-box;
  float: right;
  line-height: 22px;
  position: relative;
  min-width: 3rem;
  padding: 0 6px;
  font-size: 1rem;
  height: 22px;
  color: #757575;
  background-color: inherit;
  ${isBlock};
  ${isBadge};
`;
```
background-color: inherit; 
always, regardless of the presence of a variable badge=true and color=some color,
and in styles there is a variable, but not applicable

**Comment by paxarpp** [comment]
broke redefinition all over my project

**Comment by lttb** [comment]
Hi @paxarpp, thank you very much for the issue again!

I really appreciate your help with `styled-components`, we don't use it in our project, thus it's quite difficult to me to check the real-world examples and problems, to be sure that reshadow is compatible with SC API. This way your issues are a huge step for the production-ready version for the replacement of styled-components 🙂 

There was an issue with mixins order, and I fixed that in `alpha.60` 😄

**Comment by paxarpp** [comment]
v  .60 ok
