### ISSUE TITLE
ParseError: Identifier is expected

### ISSUE THREAD

**Issue by s0kil** [lttb/reshadow#26]
When using `@reshadow/postcss` there is an error parsing this code:
```html
<style reshadow>
  h1 {
    color: var(--color);
  }

  container {
    display: flex;
    flex-direction: column;
    padding: 10px;
    align-items: center;

    & button + button {
      margin-top: 10px;
    }
  }

  button {
    padding: 5px 10px;
    border-radius: 5px;
    font-size: 16px;
  }

  button[|size="s"] {
    font-size: 16px;
  }
</style>

<container>
  <button :size="s">Small</button>
  <button :size="m">Medium</button>
</container>
```

Error:
```bash
[!] (svelte plugin) ParseError: Identifier is expected
src/components/Button.svelte
10:     align-items: center;
11: 
12:     & .__button + .__button {
        ^
13:       margin-top: 10px;
14:     }
ParseError: Identifier is expected
```

**Comment by lttb** [comment]
Thank you for the issue! Could you provide your `preprocess` config please?

**Comment by s0kil** [comment]
Here it is:
```javascript
    svelte({
      dev: !production,

      preprocess: sveltepreprocess({
        postcss: {
          plugins: [require("@reshadow/postcss")]
        }
      }),

      css: css => {
        css.write("dist/bundle.css");
      }
    }),
```

**Comment by s0kil** [comment]
I also want to note that if I use `@reshadow/svelte/preprocess` instead, it compiles, but there is a runtime error: `Uncaught ReferenceError: __styled__ is not defined`, and some warnings:
```bash
@reshadow/core (imported by src/components/Button.svelte)
(!) Unused external imports
css imported from external module '@reshadow/core' but never used
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
@reshadow/core (guessing '__styled__')
```

**Comment by lttb** [comment]
Ah, this way you need to add `postcss-plugins` that you use independently to the `plugins` array. For example, you use there [postcss-nesting](https://github.com/jonathantneal/postcss-nesting), so the config might look like

```js
plugins: [require('postcss-nesting'), require("@reshadow/postcss")]
```

You can also use [postcss-preset-env](https://github.com/csstools/postcss-preset-env/), for example, that also includes `nesting`, but the recommended way is to use `@reshadow/svelte/preprocess`, because it also maps your `html` elements to the classnames, that reshadow generates.

**Comment by lttb** [comment]
BTW, there is a WIP example with `svelte`: https://github.com/lttb/reshadow/tree/master/examples/svelte/hello-world

**Comment by s0kil** [comment]
@lttb 
Here is an online example with the same code as I have locally: [codesandbox](https://codesandbox.io/s/young-worker-pmnco)

**Comment by lttb** [comment]
> Here is an online example with the same code as I have locally: codesandbox

Thank you very much! I think I found a bug, so I'm going to fix 😄

**Comment by s0kil** [comment]
I have tried the latest version, and it throws a different runtime error:
```bash
Button.svelte:28 Uncaught ReferenceError: require is not defined
```

**Comment by lttb** [comment]
hi @s0kil, could you try again with `0.0.1-alpha.63` please? An example from your comment works well locally with that version

**Comment by s0kil** [comment]
@lttb It works only if I manually install `@reshadow/core`.

**Comment by lttb** [comment]
@s0kil thank you for the response!

I made an example working on the codesanbox with rollup, and there was no need to install the `@reshadow/core` manually: https://codesandbox.io/s/modest-voice-fspeh.

Could you tell please, do you have any runtime error without `@reshadow/core`?

**Comment by s0kil** [comment]
@lttb Yes it's working as expected now.
