### ISSUE TITLE
 Strange behavior on windows

### ISSUE THREAD

**Issue by rnskv** [lttb/reshadow#44]
On mac os, the behavior is expected. The same project on windows throws an next error:
ERROR in /.cache/reshadow/3267209689_1.css (CssSyntaxError)

For example: 
Unknown word

  1 | .___img_80kx0_1.__use--cover_80kx0_1 {\r
  2 |     -o-object-fit: cover;\r
  3 |        object-fit: cover\r
  4 | }

Full error's stack trace:

ERROR in /.cache/reshadow/1610543195_1.css (/Users/rnskv/WebstormProjects/work4day/client/node_modules/css-loader/dist/cjs.js!/.cache/reshadow/1610543195_1.css)
Module build failed (from /Users/rnskv/WebstormProjects/work4day/client/node_modules/css-loader/dist/cjs.js):
CssSyntaxError

(2:5) Unknown word

  1 | .___Button_59g3x_1 {\r
> 2 |     margin-top: 12px;\r
    |     ^
  3 | }\r

**Comment by lttb** [comment]
Thank you for the issue! It was fixed in `0.0.1-alpha.68`, but feel free to reopen it if you'll face with this problem again.
